### PR TITLE
Add Docker environment & web demo

### PR DESCRIPTION
**Pull request by CJWBW**
This pull request makes it possible to run your model inside a Docker environment, which makes it easier for other people to run it.  We're using an open source tool called [Cog](https://github.com/replicate/cog) to make this process easier.

This also means we can make a web page where other people can try out your model! View it here: https://replicate.com/facebookresearch/omnivore. We enable selecting different models for inference, and you can find the docker file under the tab ‘run model with docker’. 

We have added some examples to the page, but do claim the page so you can own the page, customise the Example gallery as you like, push any future update to the web demo, and we'll feature it on our website and tweet about it too. 

In case you're wondering who I am, I'm from [Replicate](https://replicate.com/home), where we're trying to make machine learning reproducible. We got frustrated that we couldn't run all the really interesting ML work being done. So, we're going round implementing models we like. 😊

### CODE REVIEW

**Comment by imisra** [comment]
Hi @CJWBW 

Really appreciate this web demo and the Docker environment! `Cog` is really cool, and something we will explore for future projects too :) Thanks again!

A bit unrelated, but I'm a big fan of your team's work on arxiv-vanity.

**Comment by CJWBW** [comment]
Hi @imisra,

Thank you so much for the support of our work, glad to hear!

I noticed the model is not yet claimed, we'd appreciate if you could claim the model, so we could feature it on our website.
Anyone with a Github account from the facebookresearch orgs can claim it! The 'Claim the model' button can be found on the top of the page https://replicate.com/facebookresearch/omnivore :) 

Cheers!

**Comment by imisra** [comment]
Thanks @CJWBW, I just claimed it :)

**Comment by zeke** [comment]
Hey @imisra 👋🏼 

Thanks for claiming this model. You've been added to the [facebookresearch](https://replicate.com/facebookresearch) organization on Replicate.com, alongside @ArantxaCasanova 🎉 

Screen Shot 2022-01-31 at 8 14 37 PM

**Pull request merged**
